name: embeddings_explorer
description: A web application for exploring and managing embeddings.
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  async: ^2.13.0
  aws_common: ^0.7.10
  built_collection: ^5.1.1
  built_value: ^8.11.2
  clock: ^1.1.2
  collection: ^1.19.1
  csv: ^6.0.0
  fixnum: ^1.1.1
  freezed_annotation: ^3.1.0
  googleai_dart: ^0.1.3
  http: ^1.5.0
  jaspr: ^0.21.1
  jaspr_router: ^0.7.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.17.0
  ollama_dart: ^0.2.5
  openai_dart: ^0.5.5
  path: ^1.9.1
  pool: ^1.5.1
  retry: ^3.1.2
  sqlite3: ^2.9.0
  sqlparser: ^0.41.2
  stack_trace: ^1.12.1
  stream_transform: ^2.1.1
  timing: ^1.0.2
  web: ^1.1.1
  worker_bee:
    path: third_party/worker_bee

dev_dependencies:
  _embeddings_explorer_tool:
    path: ./tool
  build_runner: ^2.8.0
  build_test: ^3.3.3
  build_web_compilers: ^4.2.3
  built_value_generator: ^8.11.0
  freezed: ^3.2.3
  jaspr_builder: ^0.21.1
  jaspr_test: ^0.21.1
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.26.3

jaspr:
  mode: client
