name: embeddings_explorer
description: A new Jaspr project
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.10.0-0

dependencies:
  aws_common: ^0.7.10
  built_collection: ^5.1.1
  built_value: ^8.11.2
  collection: ^1.19.1
  csv: ^6.0.0
  fixnum: ^1.1.1
  jaspr: ^0.21.0-dev.1
  jaspr_router: ^0.7.1
  logging: ^1.3.0
  meta: ^1.17.0
  sqlite3: ^2.9.0
  sqlparser: ^0.41.2
  stack_trace: ^1.12.1
  stream_transform: ^2.1.1
  web: ^1.1.1
  worker_bee: ^0.3.7

dependency_overrides:
  worker_bee:
    path: third_party/worker_bee

dev_dependencies:
  _embeddings_explorer_tool:
    path: ./tool
  build_runner: ^2.6.0
  build_test: ^3.3.3
  build_web_compilers: ^4.2.3
  built_value_generator: ^8.11.0
  jaspr_builder: ^0.21.0-dev.1
  jaspr_lints: ^0.4.0
  jaspr_test: ^0.21.0-dev.1
  lints: ^6.0.0
  test: ^1.26.3

jaspr:
  mode: client
