builders:
  compiler:
    import: "package:_embeddings_explorer_tool/tailwind_builder.dart"
    builder_factories: [ "buildTailwind" ]
    build_extensions:
      "web/{{file}}.tw.css":
        - "web/{{file}}.css"
    auto_apply: dependents
    build_to: cache
    defaults:
      release_options:
        tailwindcss: --minify
