name: _embeddings_explorer_tool
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^7.5.9
  build: ^3.0.0
  build_modules: ^5.0.4
  code_builder: ^4.10.1
  dart_style: ^3.1.0
  glob: ^2.1.2
  path: ^1.8.3
  pub_semver: ^2.2.0
  source_gen: '>=3.0.0 <5.0.0'
  worker_bee: ^0.3.7

dev_dependencies:
  build_runner: ^2.4.0
  jaspr_web_compilers: ^4.2.3+1
  lints: ^6.0.0
