name: _embeddings_explorer_tool
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  build: ^3.0.0
  build_modules: ^5.0.4
  glob: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.4.0
  lints: ^6.0.0
